#!/usr/bin/env ansible-playbook

---
- name: Configure webserver with nginx and tls
  hosts: webservers
  gather_facts: True
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="Logged in as user {{ login.stdout }}"

    - name: print out operating system
      command: cat /dev/null
    - debug: var=ansible_distribution

    - name: Ignoring when a module returns an error
      command: /opt/myprog
      register: result
      ignore_errors: True
    - debug: var=result

    - name: Install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600
      register: result
    - debug: var=result

    - name: create directories for TLS certificates
      file: path=/etc/nginx/ssl state=directory

    - name: copy TLS key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: copy TLS certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: enable configuration
      file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
